Resources:
  Qldb:
    Type: AWS::QLDB::Ledger
    Properties:
      Name: test-qldb-ledger
      DeletionProtection: true
      PermissionsMode: ALLOW_ALL
  QldbNested:
    Type: AWS::QLDB::Ledger
    Properties:
      Name: test-qldb-ledger-nested
      DeletionProtection: true
      PermissionsMode: ALLOW_ALL
